/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.DataFinder;
import controler.DataLoader;
import controler.Exporter;
import model.DatabaseDTO;
import model.Dictionary;

/**
 *
 * @author Magdalena
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        loadFileScreen.setVisible(false);
        learnScreen.setVisible(false);
        repeatScreen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadFileScreen = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();
        pathToFile = new javax.swing.JTextField();
        loadFileButton = new javax.swing.JButton();
        returnToMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exportToFile = new javax.swing.JButton();
        menuScreen = new javax.swing.JPanel();
        openLearnModule = new javax.swing.JButton();
        javax.swing.JButton openDatabaseServiceModule = new javax.swing.JButton();
        repeatModule = new javax.swing.JButton();
        learnScreen = new javax.swing.JPanel();
        done = new javax.swing.JButton();
        showAnswer = new javax.swing.JButton();
        toRepeat = new javax.swing.JButton();
        answer = new java.awt.TextArea();
        returnMenu = new javax.swing.JButton();
        question = new java.awt.TextArea();
        showAdditionalInfoLearn = new javax.swing.JButton();
        java.awt.TextArea addNewComment = new java.awt.TextArea();
        addProperties = new javax.swing.JButton();
        repeatScreen = new javax.swing.JPanel();
        questionDone = new java.awt.TextArea();
        answerDone = new java.awt.TextArea();
        showAnswerDone = new javax.swing.JButton();
        showNext = new javax.swing.JButton();
        showAdditionalInfo = new javax.swing.JButton();
        returnToMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 510));
        setPreferredSize(new java.awt.Dimension(550, 510));

        loadFileScreen.setBackground(new java.awt.Color(204, 0, 0));
        loadFileScreen.setMaximumSize(null);
        loadFileScreen.setPreferredSize(new java.awt.Dimension(550, 510));

        banner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banner.setText("DODAJ NOWE ZADANIA");
        banner.setToolTipText("");

        pathToFile.setText("D:\\\\test.xlsx");
        pathToFile.setPreferredSize(new java.awt.Dimension(115, 20));

        loadFileButton.setText("Zaladuj plik");
        loadFileButton.setToolTipText("");
        loadFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadFileButtonMouseClicked(evt);
            }
        });

        returnToMenu.setText("<< POWRÓT DO MENU >>");
        returnToMenu.setToolTipText("");
        returnToMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnToMenuMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EXPORT PYTAN NAUCZONYCH");
        jLabel1.setToolTipText("");

        exportToFile.setText("Exportuj do pliku");
        exportToFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportToFileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loadFileScreenLayout = new javax.swing.GroupLayout(loadFileScreen);
        loadFileScreen.setLayout(loadFileScreenLayout);
        loadFileScreenLayout.setHorizontalGroup(
            loadFileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadFileScreenLayout.createSequentialGroup()
                .addGroup(loadFileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loadFileScreenLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(exportToFile))
                    .addGroup(loadFileScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loadFileScreenLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(pathToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loadFileScreenLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(loadFileButton))
                    .addGroup(loadFileScreenLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(loadFileScreenLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(returnToMenu)))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        loadFileScreenLayout.setVerticalGroup(
            loadFileScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadFileScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(loadFileButton)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportToFile)
                .addGap(18, 18, 18)
                .addComponent(returnToMenu)
                .addContainerGap(589, Short.MAX_VALUE))
        );

        loadFileButton.getAccessibleContext().setAccessibleName("loadFileButton");

        menuScreen.setBackground(new java.awt.Color(0, 153, 0));
        menuScreen.setPreferredSize(new java.awt.Dimension(550, 510));

        openLearnModule.setText("Przejdz do nauki");
        openLearnModule.setToolTipText("");
        openLearnModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openLearnModuleMouseClicked(evt);
            }
        });

        openDatabaseServiceModule.setText("Zarzadzaj zadaniami");
        openDatabaseServiceModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openDatabaseServiceModuleMouseClicked(evt);
            }
        });

        repeatModule.setText("Przejdź do powtórki");
        repeatModule.setToolTipText("");
        repeatModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repeatModuleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuScreenLayout = new javax.swing.GroupLayout(menuScreen);
        menuScreen.setLayout(menuScreenLayout);
        menuScreenLayout.setHorizontalGroup(
            menuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuScreenLayout.createSequentialGroup()
                .addGroup(menuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuScreenLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(repeatModule, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(openLearnModule, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuScreenLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(openDatabaseServiceModule, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        menuScreenLayout.setVerticalGroup(
            menuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuScreenLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(menuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatModule, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openLearnModule, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(openDatabaseServiceModule, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        learnScreen.setBackground(new java.awt.Color(0, 51, 204));
        learnScreen.setMaximumSize(new java.awt.Dimension(550, 510));
        learnScreen.setName(""); // NOI18N
        learnScreen.setPreferredSize(new java.awt.Dimension(550, 510));

        done.setText("Umiem");
        done.setToolTipText("");
        done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneMouseClicked(evt);
            }
        });

        showAnswer.setText("Pokaż odpowiedź");
        showAnswer.setToolTipText("");
        showAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAnswerMouseClicked(evt);
            }
        });

        toRepeat.setText("Nie umiem");
        toRepeat.setToolTipText("");
        toRepeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toRepeatMouseClicked(evt);
            }
        });

        answer.setMaximumSize(new java.awt.Dimension(400, 50));
        answer.setText("Tekst do dodania");

        returnMenu.setText("<<KONIEC>>");
        returnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnMenuMouseClicked(evt);
            }
        });

        question.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        question.setMaximumSize(new java.awt.Dimension(400, 80));

        showAdditionalInfoLearn.setText("Podpowiedź");
        showAdditionalInfoLearn.setToolTipText("");
        showAdditionalInfoLearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAdditionalInfoLearnMouseClicked(evt);
            }
        });

        addNewComment.setMaximumSize(new java.awt.Dimension(400, 50));
        addNewComment.setName(""); // NOI18N

        addProperties.setText("Dopisz");
        addProperties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPropertiesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout learnScreenLayout = new javax.swing.GroupLayout(learnScreen);
        learnScreen.setLayout(learnScreenLayout);
        learnScreenLayout.setHorizontalGroup(
            learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(learnScreenLayout.createSequentialGroup()
                .addGroup(learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(learnScreenLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(learnScreenLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(done)
                        .addGap(18, 18, 18)
                        .addComponent(toRepeat)
                        .addGap(24, 24, 24)
                        .addComponent(addProperties)
                        .addGap(18, 18, 18)
                        .addComponent(returnMenu))
                    .addGroup(learnScreenLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNewComment, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showAdditionalInfoLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        learnScreenLayout.setVerticalGroup(
            learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(learnScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(showAdditionalInfoLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(learnScreenLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(addNewComment, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, learnScreenLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(learnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(done)
                    .addComponent(toRepeat)
                    .addComponent(returnMenu)
                    .addComponent(addProperties))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        repeatScreen.setBackground(new java.awt.Color(153, 0, 153));
        repeatScreen.setMaximumSize(new java.awt.Dimension(550, 510));
        repeatScreen.setMinimumSize(new java.awt.Dimension(550, 510));

        showAnswerDone.setText("Pokaż odpowiedź");
        showAnswerDone.setToolTipText("");
        showAnswerDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAnswerDoneMouseClicked(evt);
            }
        });

        showNext.setText("Pokaż kolejne pytanie");
        showNext.setToolTipText("");
        showNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showNextMouseClicked(evt);
            }
        });

        showAdditionalInfo.setText("Dodatkowe info");
        showAdditionalInfo.setToolTipText("");
        showAdditionalInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAdditionalInfoMouseClicked(evt);
            }
        });

        returnToMainMenu.setText("<< POWRÓT >>");
        returnToMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnToMainMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout repeatScreenLayout = new javax.swing.GroupLayout(repeatScreen);
        repeatScreen.setLayout(repeatScreenLayout);
        repeatScreenLayout.setHorizontalGroup(
            repeatScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repeatScreenLayout.createSequentialGroup()
                .addGroup(repeatScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(repeatScreenLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(repeatScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(questionDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answerDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(repeatScreenLayout.createSequentialGroup()
                                .addComponent(showAnswerDone)
                                .addGap(18, 18, 18)
                                .addComponent(showAdditionalInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showNext))))
                    .addGroup(repeatScreenLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(returnToMainMenu)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        repeatScreenLayout.setVerticalGroup(
            repeatScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repeatScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(repeatScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAnswerDone)
                    .addComponent(showAdditionalInfo)
                    .addComponent(showNext))
                .addGap(18, 18, 18)
                .addComponent(answerDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnToMainMenu)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadFileScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(learnScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(repeatScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadFileScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(learnScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(repeatScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadFileButtonMouseClicked
        try {
            banner.setText("DODAJ NOWE ZADANIA");
            String path = pathToFile.getText();
            DataLoader dataLoader = new DataLoader();
            dataLoader.importDataFromFileToDatabase(path);
            loadFileScreen.setVisible(false);
            menuScreen.setVisible(true);
        } catch (Exception ex) {
            banner.setText("Blad podczas czytania pliku - upewnij się, że ścieżka jest podana poprawnie");
        }

    }//GEN-LAST:event_loadFileButtonMouseClicked

    private void openLearnModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openLearnModuleMouseClicked
        menuScreen.setVisible(false);
        learnScreen.setVisible(true);

        generateQuestion();
    }//GEN-LAST:event_openLearnModuleMouseClicked

    private void generateQuestion() {
        databaseDTO = new DataFinder().randomRecord(Dictionary.QUESTIONS_TO_DO_TABLE);
        System.err.println("Wylosowano pytanie z id: ");
        System.err.println(databaseDTO.getId().toString());
        question.setText(databaseDTO.getQuestion());
        answer.setText("");

    }

    private void generateDoneQuestion() {
        databaseDTO = new DataFinder().randomRecord(Dictionary.QUESTIONS_DONE);
        System.err.println("Wylosowano pytanie z id: ");
        System.err.println(databaseDTO.getId().toString());
        questionDone.setText(databaseDTO.getQuestion());
        answerDone.setText("");

    }

    private void openDatabaseServiceModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openDatabaseServiceModuleMouseClicked
        menuScreen.setVisible(false);
        loadFileScreen.setVisible(true);
        exportToFile.setText("Exportuj do pliku");
    }//GEN-LAST:event_openDatabaseServiceModuleMouseClicked

    private void returnToMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnToMenuMouseClicked
        menuScreen.setVisible(true);
        loadFileScreen.setVisible(false);
    }//GEN-LAST:event_returnToMenuMouseClicked

    private void returnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnMenuMouseClicked
        learnScreen.setVisible(false);
        menuScreen.setVisible(true);
    }//GEN-LAST:event_returnMenuMouseClicked

    private void showAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAnswerMouseClicked
        // answer.setVisible(true);
        answer.setText(databaseDTO.getAnswer());
    }//GEN-LAST:event_showAnswerMouseClicked

    private void doneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneMouseClicked
        new DataFinder().moveToDoneTable(databaseDTO);
        generateQuestion();
    }//GEN-LAST:event_doneMouseClicked

    private void toRepeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toRepeatMouseClicked
        generateQuestion();
    }//GEN-LAST:event_toRepeatMouseClicked

    private void repeatModuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repeatModuleMouseClicked
        menuScreen.setVisible(false);
        repeatScreen.setVisible(true);

        generateDoneQuestion();
    }//GEN-LAST:event_repeatModuleMouseClicked

    private void showAnswerDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAnswerDoneMouseClicked
        answerDone.setText(databaseDTO.getAnswer());
    }//GEN-LAST:event_showAnswerDoneMouseClicked

    private void showNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showNextMouseClicked
        generateDoneQuestion();
    }//GEN-LAST:event_showNextMouseClicked

    private void showAdditionalInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAdditionalInfoMouseClicked
        answerDone.setText(buildAddtionalInfoField());
    }//GEN-LAST:event_showAdditionalInfoMouseClicked

    private void returnToMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnToMainMenuMouseClicked
        menuScreen.setVisible(true);
        repeatScreen.setVisible(false);
    }//GEN-LAST:event_returnToMainMenuMouseClicked

    private void exportToFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportToFileMouseClicked
        Exporter exporter = new Exporter();
        if (exporter.exportDoneQuestionToXls()) {
            exportToFile.setText("ZAPISANO");
        } else {
            exportToFile.setText("Błąd podczas zapisu");
        }

    }//GEN-LAST:event_exportToFileMouseClicked

    private void showAdditionalInfoLearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAdditionalInfoLearnMouseClicked
        answer.setText(buildAddtionalInfoField());
    }//GEN-LAST:event_showAdditionalInfoLearnMouseClicked

    private void addPropertiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPropertiesMouseClicked

        String text = answer.getText();
        DataFinder dataFinder = new DataFinder();
        dataFinder.makeUpdateOfComment(databaseDTO, text);

    }//GEN-LAST:event_addPropertiesMouseClicked

    private String buildAddtionalInfoField() {
        StringBuilder sb = new StringBuilder();
        sb.append("Numer slajdu: ");
        sb.append(databaseDTO.getNumberOfSlide());
        sb.append("\n");
        sb.append("Komentarz: ");
        sb.append(databaseDTO.getComments());

        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProperties;
    private java.awt.TextArea answer;
    private java.awt.TextArea answerDone;
    private javax.swing.JLabel banner;
    private javax.swing.JButton done;
    private javax.swing.JButton exportToFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel learnScreen;
    private javax.swing.JButton loadFileButton;
    private javax.swing.JPanel loadFileScreen;
    private javax.swing.JPanel menuScreen;
    private javax.swing.JButton openLearnModule;
    private javax.swing.JTextField pathToFile;
    private java.awt.TextArea question;
    private java.awt.TextArea questionDone;
    private javax.swing.JButton repeatModule;
    private javax.swing.JPanel repeatScreen;
    private javax.swing.JButton returnMenu;
    private javax.swing.JButton returnToMainMenu;
    private javax.swing.JButton returnToMenu;
    private javax.swing.JButton showAdditionalInfo;
    private javax.swing.JButton showAdditionalInfoLearn;
    private javax.swing.JButton showAnswer;
    private javax.swing.JButton showAnswerDone;
    private javax.swing.JButton showNext;
    private javax.swing.JButton toRepeat;
    // End of variables declaration//GEN-END:variables
    private DatabaseDTO databaseDTO;

}
